version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    environment:
      DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
    steps:
      - checkout
      - run:
          name: Install Cake
          command: |
            cat << \EOF >> ~/.bash_profile
            # Add .NET Core SDK tools
            export PATH="$PATH:/root/.dotnet/tools"
            EOF
            dotnet tool install -g Cake.Tool
            #echo 'export PATH=$PATH:/root/.dotnet/tools' >> $BASH_ENV
            source ~/.bash_profile
      - run:
          name: Build
          command: dotnet cake build.cake --runtime=linux-x64
